#!/usr/bin/env bash

#Datenbank Variabeln
DBHOST=localhost
DBNAME=M300
DBUSER=m300
DBPASSWD=berger
DBTSCHUELER=user
TABLE1=Basketball
Table2=Fussball

# Die Paketen werden geupdated
sudo apt-get update

# konfigurieren von mysql und phpadmin und mit Datenbank verbinden
debconf-set-selections <<< "mysql-server mysql-server/root_password password $DBPASSWD"
debconf-set-selections <<< "mysql-server mysql-server/root_password_again password $DBPASSWD"
debconf-set-selections <<< "phpmyadmin phpmyadmin/dbconfig-install boolean true"
debconf-set-selections <<< "phpmyadmin phpmyadmin/app-password-confirm password $DBPASSWD"
debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/admin-pass password $DBPASSWD"
debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/app-pass password $DBPASSWD"
debconf-set-selections <<< "phpmyadmin phpmyadmin/reconfigure-webserver multiselect none"

# Interface von mysql und phpadmin installieren
sudo apt-get -y install mysql-server phpmyadmin

# Tabellen und Datenbank erstellen 
mysql -uroot -p$DBPASSWD <<%EOF%
	CREATE USER '$DBUSER'@'$DBHOST' IDENTIFIED BY '$DBPASSWD';
	GRANT ALL PRIVILEGES ON *.* TO '$DBUSER'@'$DBHOST' IDENTIFIED BY '$DBPASSWD' WITH GRANT OPTION;
	FLUSH PRIVILEGES;
	CREATE DATABASE $DBNAME;
	USE $DBNAME;
	CREATE TABLE $TABLE1 (PersonID INT(50), Vorname VARCHAR(50), Name VARCHAR(50), PRIMARY Key (PersonID));
	INSERT INTO $TABLE1 VALUE ("1","Kevin","Durant");
	INSERT INTO $TABLE1 VALUE ("2","Kyrie","Irving");
	INSERT INTO $TABLE1 VALUE ("3","James","Harden");
	INSERT INTO $TABLE1 VALUE ("4","Lebron","James");
	quit
%EOF%	

cd /vagrant

# Den Remote Zugriff auf die Datenbank durch updaten der mmysql conf
sudo sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mysql.conf.d/mysqld.cnf

sudo service mysql restart

# setup phpmyadmin

sudo service apache2 restart