#!/usr/bin/env bash

#Datenbank Variabeln
DBHOST=localhost
DBNAME=M300
DBUSER=root
DBPASSWD=root
DBTSCHUELER=user
TABLE1=Basketball
TABLE2=Fusball

# Die Paketen werden geupdated
sudo apt-get update

# konfigurieren von mysql und phpadmin und mit Datenbank verbinden
debconf-set-selections <<< "mysql-server mysql-server/root_password password $DBPASSWD"
debconf-set-selections <<< "mysql-server mysql-server/root_password_again password $DBPASSWD"
debconf-set-selections <<< "phpmyadmin phpmyadmin/dbconfig-install boolean true"
debconf-set-selections <<< "phpmyadmin phpmyadmin/app-password-confirm password $DBPASSWD"
debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/admin-pass password $DBPASSWD"
debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/app-pass password $DBPASSWD"
debconf-set-selections <<< "phpmyadmin phpmyadmin/reconfigure-webserver multiselect none"

# Interface von mysql und phpadmin installieren
sudo apt-get -y install mysql-server phpmyadmin

# Tabellen und Datenbank erstellen 
mysql -uroot -p$DBPASSWD <<%EOF%
	CREATE USER '$DBUSER'@'$DBHOST' IDENTIFIED BY '$DBPASSWD';
	GRANT ALL PRIVILEGES ON *.* TO '$DBUSER'@'$DBHOST' IDENTIFIED BY '$DBPASSWD' WITH GRANT OPTION;
	FLUSH PRIVILEGES;
	CREATE DATABASE $DBNAME;
	USE $DBNAME;
	CREATE TABLE $TABLE1(PersonID INT(50), Vorname VARCHAR(50), Name VARCHAR(50), Trikot Nummer (PersonID));
	CREATE TABLE $TABLE2 (TrikotID INT(50), Club VARCHAR(50), PersonID INT(50), Trikot Nummer (TrikotID), FOREIGN KEY (PersonID) REFERENCES Spieler(PersonID));
	INSERT INTO $TABLE1 VALUE ("1","Kevin","Durant","7");
	INSERT INTO $TABLE1 VALUE ("2","Kyrie","Irving","11");
	INSERT INTO $TABLE1 VALUE ("3","James","Harden","1");
	INSERT INTO $TABLE1 VALUE ("4","Lebron","James","6");
	INSERT INTO $TABLE2 VALUE ("1","BKN", "7", "1" );
	INSERT INTO $TABLE2 VALUE ("2","BKN", "11", "2" );
	INSERT INTO $TABLE2 VALUE ("3","PHI", "1", "3" );
	INSERT INTO $TABLE2 VALUE ("4","LAL", "6", "4" );
	quit
%EOF%	

cd /vagrant

# Den Remote Zugriff auf die Datenbank durch updaten der mmysql conf
sudo sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mysql.conf.d/mysqld.cnf

sudo service mysql restart

# setup phpmyadmin

sudo service apache2 restart